//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigersProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class lekce
    {
        public int ID { get; set; }
        public string jmenoKlient { get; set; }
        public string prijmeniKlient { get; set; }
        public string TELEFON { get; set; }
        public string MISTO { get; set; }
        public int OSOB { get; set; }
        public short PLACENO { get; set; }
        public string POZNAMKA { get; set; }
        public System.DateTime ZACATEK { get; set; }
        public float DELKA { get; set; }
        public int instruktor_id { get; set; }
        public int jazyk_id { get; set; }
        public int druh_id { get; set; }
        public Nullable<System.DateTime> DATUM { get; set; }
    
        public virtual druh druh { get; set; }
        public virtual instruktor instruktor { get; set; }
        public virtual jazyk jazyk { get; set; }
    }
}
