//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigersProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dispozice> dispozice { get; set; }
        public virtual DbSet<druh> druh { get; set; }
        public virtual DbSet<instruktor> instruktor { get; set; }
        public virtual DbSet<jazyk> jazyk { get; set; }
        public virtual DbSet<lekce> lekce { get; set; }
    }
}
